name: Promax AV
favicon: null
layout_spectrum: 0.88963
typography_spectrum: 0.74074
title: Draft website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#012d6a'
    - '#c1d72d'
    - '#afbdd1'
    - '#7c92b2'
  brandStrength: 0.5
  lightness: 0.928923106752336
  saturation: 0.955271813319996
  rhythmicContrast: 0.16103204968385398
purpose: []
